// Code generated by go-swagger; DO NOT EDIT.

package service_plugin_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"cli/pkg/client/platformservice/openapi2/models"
)

// NewUpdateLootBoxPluginConfigParams creates a new UpdateLootBoxPluginConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpdateLootBoxPluginConfigParams() *UpdateLootBoxPluginConfigParams {
	return &UpdateLootBoxPluginConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateLootBoxPluginConfigParamsWithTimeout creates a new UpdateLootBoxPluginConfigParams object
// with the ability to set a timeout on a request.
func NewUpdateLootBoxPluginConfigParamsWithTimeout(timeout time.Duration) *UpdateLootBoxPluginConfigParams {
	return &UpdateLootBoxPluginConfigParams{
		timeout: timeout,
	}
}

// NewUpdateLootBoxPluginConfigParamsWithContext creates a new UpdateLootBoxPluginConfigParams object
// with the ability to set a context for a request.
func NewUpdateLootBoxPluginConfigParamsWithContext(ctx context.Context) *UpdateLootBoxPluginConfigParams {
	return &UpdateLootBoxPluginConfigParams{
		Context: ctx,
	}
}

// NewUpdateLootBoxPluginConfigParamsWithHTTPClient creates a new UpdateLootBoxPluginConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpdateLootBoxPluginConfigParamsWithHTTPClient(client *http.Client) *UpdateLootBoxPluginConfigParams {
	return &UpdateLootBoxPluginConfigParams{
		HTTPClient: client,
	}
}

/*
UpdateLootBoxPluginConfigParams contains all the parameters to send to the API endpoint

	for the update loot box plugin config operation.

	Typically these are written to a http.Request.
*/
type UpdateLootBoxPluginConfigParams struct {

	// Body.
	Body *models.LootBoxPluginConfigUpdate

	// Namespace.
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the update loot box plugin config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateLootBoxPluginConfigParams) WithDefaults() *UpdateLootBoxPluginConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the update loot box plugin config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpdateLootBoxPluginConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) WithTimeout(timeout time.Duration) *UpdateLootBoxPluginConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) WithContext(ctx context.Context) *UpdateLootBoxPluginConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) WithHTTPClient(client *http.Client) *UpdateLootBoxPluginConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) WithBody(body *models.LootBoxPluginConfigUpdate) *UpdateLootBoxPluginConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) SetBody(body *models.LootBoxPluginConfigUpdate) {
	o.Body = body
}

// WithNamespace adds the namespace to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) WithNamespace(namespace string) *UpdateLootBoxPluginConfigParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the update loot box plugin config params
func (o *UpdateLootBoxPluginConfigParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateLootBoxPluginConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
