// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BaseTLSConfig base TLS config
//
// swagger:model BaseTLSConfig
type BaseTLSConfig struct {

	// root cert file name
	RootCertFileName string `json:"rootCertFileName,omitempty"`
}

// Validate validates this base TLS config
func (m *BaseTLSConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this base TLS config based on context it is used
func (m *BaseTLSConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BaseTLSConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseTLSConfig) UnmarshalBinary(b []byte) error {
	var res BaseTLSConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
