// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PublicCustomConfigInfo public custom config info
//
// swagger:model PublicCustomConfigInfo
type PublicCustomConfigInfo struct {

	// connect type: INSECURE, TLS, default is INSECURE
	// Required: true
	// Enum: [INSECURE TLS]
	ConnectionType *string `json:"connectionType"`

	// plugin grpc server address: <host>:<port>
	// Required: true
	GrpcServerAddress *string `json:"grpcServerAddress"`

	// tls config
	TLSConfig *BaseTLSConfig `json:"tlsConfig,omitempty"`
}

// Validate validates this public custom config info
func (m *PublicCustomConfigInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGrpcServerAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTLSConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var publicCustomConfigInfoTypeConnectionTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["INSECURE","TLS"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		publicCustomConfigInfoTypeConnectionTypePropEnum = append(publicCustomConfigInfoTypeConnectionTypePropEnum, v)
	}
}

const (

	// PublicCustomConfigInfoConnectionTypeINSECURE captures enum value "INSECURE"
	PublicCustomConfigInfoConnectionTypeINSECURE string = "INSECURE"

	// PublicCustomConfigInfoConnectionTypeTLS captures enum value "TLS"
	PublicCustomConfigInfoConnectionTypeTLS string = "TLS"
)

// prop value enum
func (m *PublicCustomConfigInfo) validateConnectionTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, publicCustomConfigInfoTypeConnectionTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *PublicCustomConfigInfo) validateConnectionType(formats strfmt.Registry) error {

	if err := validate.Required("connectionType", "body", m.ConnectionType); err != nil {
		return err
	}

	// value enum
	if err := m.validateConnectionTypeEnum("connectionType", "body", *m.ConnectionType); err != nil {
		return err
	}

	return nil
}

func (m *PublicCustomConfigInfo) validateGrpcServerAddress(formats strfmt.Registry) error {

	if err := validate.Required("grpcServerAddress", "body", m.GrpcServerAddress); err != nil {
		return err
	}

	return nil
}

func (m *PublicCustomConfigInfo) validateTLSConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.TLSConfig) { // not required
		return nil
	}

	if m.TLSConfig != nil {
		if err := m.TLSConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tlsConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tlsConfig")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this public custom config info based on the context it is used
func (m *PublicCustomConfigInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTLSConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PublicCustomConfigInfo) contextValidateTLSConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.TLSConfig != nil {
		if err := m.TLSConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tlsConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tlsConfig")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PublicCustomConfigInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PublicCustomConfigInfo) UnmarshalBinary(b []byte) error {
	var res PublicCustomConfigInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
